# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/apple/MyProject/ntools/modules/wxlua/wxLua/apps/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/apple/MyProject/ntools/modules/wxlua/wxLua/apps/wxlua/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/apple/MyProject/ntools/modules/wxlua/wxLua/apps/wxluacan/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/apple/MyProject/ntools/modules/wxlua/wxLua/apps/wxluaedit/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/apple/MyProject/ntools/modules/wxlua/wxLua/apps/wxluafreeze/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/apple/MyProject/ntools/modules/wxlua/wxLua/build/CMakeFunctions.cmake))

/Users/apple/MyProject/ntools/modules/wxlua/wxLua/wxLua-build/CMakeFiles/cmake.check_cache: $(TARGETS)
	/Applications/CMake.app/Contents/bin/cmake -H/Users/apple/MyProject/ntools/modules/wxlua/wxLua -B/Users/apple/MyProject/ntools/modules/wxlua/wxLua/wxLua-build
